weights: yolov5s.pt
cfg: ''
data: C:\Users\joost\MLV1\yolov5\data\custom_dataset.yaml
hyp: data\hyps\hyp.scratch-low.yaml
epochs: 3
batch_size: 24
imgsz: 480
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs\train
name: CPU_epochs=3_batch-size=24_image-size=480_database-size=600
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\train\CPU_epochs=3_batch-size=24_image-size=480_database-size=600
